# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1029, 640)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.latitude = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.latitude.setObjectName("latitude")
        self.horizontalLayout_2.addWidget(self.latitude)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.longitude = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.longitude.setObjectName("longitude")
        self.horizontalLayout_2.addWidget(self.longitude)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.search_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_button.setObjectName("search_button")
        self.verticalLayout.addWidget(self.search_button)
        self.switch_radion_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.switch_radion_button.setObjectName("switch_radion_button")
        self.verticalLayout.addWidget(self.switch_radion_button)
        self.search = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.search.setObjectName("search")
        self.verticalLayout.addWidget(self.search)
        self.reset = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reset.setObjectName("reset")
        self.verticalLayout.addWidget(self.reset)
        self.address = QtWidgets.QLabel(parent=self.centralwidget)
        self.address.setObjectName("address")
        self.verticalLayout.addWidget(self.address)
        self.post_code_radio_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.post_code_radio_button.setObjectName("post_code_radio_button")
        self.verticalLayout.addWidget(self.post_code_radio_button)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Широта:"))
        self.label_3.setText(_translate("MainWindow", "Долгота:"))
        self.search_button.setText(_translate("MainWindow", "Поиск"))
        self.switch_radion_button.setText(_translate("MainWindow", "Светлая"))
        self.reset.setText(_translate("MainWindow", "Сброс поискового результата"))
        self.address.setText(_translate("MainWindow", "TextLabel"))
        self.post_code_radio_button.setText(_translate("MainWindow", "Почтовый индекс"))
